tests pagure: bypass weird date comp failure
this is what we are seeing in CI tests:
```
AssertionError: assert datetime.datetime(2020, 8, 31, 5, 36, 50) >=
    datetime.datetime(2020, 8, 31, 7, 0)
```

For some reason, the date in CI is 31.8. 5:36 while our test is >= 7:00

locally works fine obviously

I don't have a motivation to track down the root cause, sorry.

I suspect timezones are the root cause.

Signed-off-by: Tomas Tomecek <ttomecek@redhat.com>